update to suggest using numeric key for nested components
livewire/docs pull request #444
Opened 2022-11-23 14:05 UTC by tobya

I have found that using a unique alphanumeric key can cause issues, whereas using a numberic key seems to work consistently.  Worth specifying this in the docs.

2022-11-23 20:49 UTC, joshhanley commented
@tobya thanks for the PR! I've never run into issues using alphanumeric keys myself. Are you able to open a Livewire discussion with some example code that doesn't work so we can investigate it? Thanks!

2022-11-23 21:10 UTC, tobya commented
I'll see what I can do.  I can reproduce it easily in my codebase so I'll see if I can create a project to recreate.

2022-11-23 21:12 UTC, joshhanley commented
@tobya that'd be great, thanks!

2022-12-09 09:41 UTC, JoshSalway requested changes
"us" should be spelt "use"

2022-12-20 22:49 UTC, joshhanley commented
@tobya I'm going to close this for now. Let me know if you manage to create a discussion and I will have a look 🙂

2022-12-20 22:49 UTC, closed without merging